version: '2'

services:
  selenoid:
    network_mode: bridge
    image: aerokube/selenoid
    volumes:
      - ".:/etc/selenoid"
      - "/var/run/docker.sock:/var/run/docker.sock"
    ports:
      - "4444:4444"
    command: -limit 10 -conf browsers_docker.json

  selenoid-ui:
    network_mode: host
    image: aerokube/selenoid-ui:1.0.0
    ports:
      - "8080:8080"